### ISSUE TITLE
Short circuit evaluation of v() in an implicit template until v() is actually present

### ISSUE THREAD

**Issue by evilchia** [cydran/cydran#445]
***Occurs because v() is not yet present***
Exception message: Cannot read property 'getPage' of undefined TypeError: Cannot read property 'getPage' of undefined
    at Object.eval (eval at Getter.get (webpack-internal:///./node_modules/cydran/dist/cydran.js), <anonymous>:12:13)
    at Getter.get (webpack-internal:///./node_modules/cydran/dist/cydran.js:3164:36)
    at ModelMediatorImpl.get (webpack-internal:///./node_modules/cydran/dist/cydran.js:5250:54)
    at ModelMediatorImpl.evaluate (webpack-internal:///./node_modules/cydran/dist/cydran.js:5260:26)
    at DigestionContextImpl.digestSegment (webpack-internal:///./node_modules/cydran/dist/cydran.js:5448:36)
    at DigestionContextImpl.digest (webpack-internal:///./node_modules/cydran/dist/cydran.js:5439:18)
    at DigesterImpl.digest (webpack-internal:///./node_modules/cydran/dist/cydran.js:3235:44)
    at MvvmImpl.digest (webpack-internal:///./node_modules/cydran/dist/cydran.js:5141:27)
    at MvvmImpl.$apply (webpack-internal:///./node_modules/cydran/dist/cydran.js:5167:14)
    at ComponentInternalsImpl.$apply (webpack-internal:///./node_modules/cydran/dist/cydran.js:2562:23)

***Current Workaround***
v()?.something

**Comment by evilchia** [comment]
This may have been addressed with the recent merge of lifecycle state/machine refactoring.

**Comment by matthewwerny** [comment]
It wasn't.

**Comment by matthewwerny** [comment]
It was.
